import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import IntroAnimation from "@/components/IntroAnimation";
import ChefChat from "@/components/ChefChat";
import AdminDashboard from "@/components/AdminDashboard";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // In a real app, we check session role here (e.g. user.role === 'super_admin')
  const isGodMode = false; // Disabled by default (Enable for testing)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IntroAnimation />
        <AdminDashboard isVisible={true} /> {/* Enabled for testing */}
        <ChefChat />
        {children}
      </body>
    </html>
  );
}
